## railway.toml

[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "streamlit run automated_platform/main.py --server.port $PORT --server.address 0.0.0.0 --server.baseUrlPath /"
healthcheckPath = "/"
healthcheckTimeout = 200
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[variables]
STREAMLIT_SERVER_PORT = "${PORT}"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ENABLE_CORS = "true"